spring:
  application:
    name: wiremock-handler
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include: health,beans

net:
  snytkine:
    wiremock-rest-client-middleware:
      enabled: true
      mocks-directory: mocks
