spring:
  application:
    name: wiremock-handler
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
      base-path: /actuator
  endpoint:
    beans:
      enabled: true

logging:
  level:
    net.snytkine.wiremock_middleware.middleware: TRACE

net:
  snytkine:
    rest-client-middleware:
      wiremock:
        enabled: true
        templating-enabled: true
        mappings-class-path: "mappings"
        mock-response-header: X-Wiremock-Response
