spring:
  application:
    name: wiremock-handler
server:
  port: 8088
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
      base-path: /actuator
  endpoint:
    beans:
      enabled: true

logging:
  level:
    net.snytkine.wiremock_middleware.middleware: TRACE

net:
  snytkine:
    rest-client-wiremock-interceptor:
      enabled: true
      mock-response-header: X-Mock-Response
      mock-response-header-value: wiremock-middleware
      templating-enabled: true
      mappings-class-path: mappings
